### ISSUE TITLE
Problem with syncing

### ISSUE THREAD

**Issue by lfini** [cpbotha/nvpy#177]
I've installed the latest stable version from github several days ago. I've noticed a repeatable problem related to syncing to simplenote site.

Here are the symptoms: occasionally if I update a note, close nvpy and raestart it later on, I find nvpy unusable. After starting up it stops in post_mortem debug with:

> /usr/local/lib/python2.7/dist-packages/nvpy-1.0.0-py2.7.egg/nvpy/view.py(456)append()
-> modifydate = float(note.get('modifydate'))
(Pdb) 

At this point the GUI is unresponsive and the debugger is not usable (the terminal does not accept typing)

The problem arises because the note modified in the previous session, when downloaded from the simplenote site has not a field "modifydate", so the note.get('modifydate') returns None and raises the exception.

**Comment by yuuki0xff** [comment]
If nvpy crashes immediately after startup, the local cache will be corrupted.  I released the [nvpy v1.1.0](https://github.com/cpbotha/nvpy/releases/tag/v1.1.0) in just the other day.  Please upgrade to nvpy v1.1.0 and delete `~/.nvpy` directory to clear the local cache.
If the problem persists even, please report more detail info.

> The problem arises because the note modified in the previous session, when downloaded from the simplenote site has not a field "modifydate", so the note.get('modifydate') returns None and raises the exception.

The latest version of simplenote library add the `modifydate` field to all responses for ensure backward compatibility.  So in normal cases, this problem is not occur.
https://github.com/mrtazz/simplenote.py/blob/v2.1.0/simplenote/simplenote.py#L365

**Comment by yuuki0xff** [comment]
If the issue persists, please reopen this issue.
