### ISSUE TITLE
Syncing not getting note list after upgrade

### ISSUE THREAD

**Issue by volt4ire** [cpbotha/nvpy#178]
After upgrading to version 1.1 on Ubuntu 18.10 via pip, I am now getting the sync error message of "could not get note list from server." I tried removing my .nvpy directory and recreating my .nvpy.cfg file with my simplenote credentials but it has not fixed the error. 

My nvpy.log states:
2019-04-02 06:15:06,027 - DEBUG - nvpy logging initialized
2019-04-02 06:15:06,028 - DEBUG - config read from ['/home/rwbarat/.nvpy.cfg']
2019-04-02 06:15:06,219 - DEBUG - Starting full sync.
2019-04-02 06:15:06,221 - DEBUG - Retrieving full note list from server, could take a while.

**Comment by rakslice** [comment]
Perhaps the embedded simplenote library needs an update.

I was getting this behaviour when trying to use nvpy installed via pip.

I moved nvpy's embedded copy of the simplenote library out of the way in site-packages, and installed the latest simplenote via pip, and after that nvpy worked.

**Comment by volt4ire** [comment]
Thanks for this info! What exactly did this entail? I just tried removing simplenote from ~/.local/lib/python2.7/site-packages/ and upgrading to the [latest simplenote version (2.1.2)](https://github.com/mrtazz/simplenote.py/releases) via 'pip upgrade simplenote' and reinstalling nvpy via 'pip install --upgrade 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'' but the problem still persists.

**Comment by rakslice** [comment]
You have to move the embedded copy of simplenote within nvpy out of the way; because of the way imports in python use paths, nvpy won't use a separate copy of the simplenote library if there is still one in its directory

**Comment by volt4ire** [comment]
Thanks where is the file path of the embedded copy simplenote?

**Comment by rakslice** [comment]
If your nvpy is in ~/.local/lib/python2.7/site-packages/nvpy, it would be ~/.local/lib/python2.7/site-packages/nvpy/simplenote.py

**Comment by volt4ire** [comment]
Thanks yeah I didn't have that file so the problem still persists for me

**Comment by yuuki0xff** [comment]
Nvpy v1.1.0 removed embeded simplenote client library.  So `~/.local/lib/python2.7/site-packages/nvpy/simplenote.py` should not exist.
The embeded simplenote client library has been removed since nvpy v1.1.0.  So `~/.local/lib/python2.7/site-packages/nvpy/simplenote.py` should not exist.

Nvpy requires the "simplenote" package.  Make sure that you have the simplenote v2.1.0 and nvpy v1.1.0 are installed by the following command.
```
$ pip2 list |grep nvpy
nvpy      1.1.0
$ pip2 list |grep simplenote
simplenote     2.1.0
```

If above packages is already installed, the package content may be broken.  Please remove the following directories/files.
* `~/.local/lib/python2.7/site-packages/nvpy*`
* `~/.local/lib/python2.7/site-packages/simplenote*`

And re-install the nvpy.
```
$ pip install --upgrade --user nvpy
```

**Comment by yuuki0xff** [comment]
This issue will be solved by upgrading the nvpy package and dependencies packages.  If the issue persists, please reopen this issue.
