### ISSUE TITLE
Full Syncing non stop

### ISSUE THREAD

**Issue by grandfso** [cpbotha/nvpy#182]
Hello, 
when I launch the latest version of the app (1.2.1 from PyPi), it constantly says 'Full Syncing'. Nothing interesting appears in the logs.

```
2019-07-16 11:50:27,163 - DEBUG - nvpy logging initialized
2019-07-16 11:50:27,163 - DEBUG - config read from ['/home/grand/.nvpy.cfg']
2019-07-16 11:50:27,448 - DEBUG - Starting full sync.
2019-07-16 11:50:27,499 - DEBUG - Retrieving full note list from server, could take a while.

```

**Comment by yuuki0xff** [comment]
The same issue has been confirmed in my environment from before June 24, 2019. Probably, the full sync is running. it takes a very long time.

I investigated this issue with packet capture, I confirmed the following.
1. nvPY sends valid request to API server.
2. API server reply quickly.
3. About two seconds after TCP connection, a large amount of packet lost continuously, and TCP throughput was extremely reduced.

The point is that download speed is very slow, but the download is ongoing.  The same behavior was confirmed using several different networks [1], so I suspects that a band-limiting device exists on the route.

For this problem, what nvPY can do is limited.  Because nvPY can not determine reason for the download speed issue whether narrow band network or band-limiting.  If you have any good ideas, please let me know.

[1]: Tested on mobile, CATV line and university network

**Comment by yuuki0xff** [comment]
I added a workaround and pushed to master branch.  Please try it.

```
$ python2 -m pip install --upgrade 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
$ nvpy
```

**Comment by grandfso** [comment]
I did install the latest version and it is working fine. Many thanks.
