### ISSUE TITLE
So . . . MacOS?

### ISSUE THREAD

**Issue by m0rg5** [cpbotha/nvpy#228]
Can't see any instruction or download for MacOS

**Comment by yuuki0xff** [comment]
I briefly wrote about macOS in the installation docs.

d29ad9ed88c472267220fe01b04db8e0ea8a62ae

**Comment by m0rg5** [comment]
So, no plans to fix I take it?

**Comment by yuuki0xff** [comment]
Yes, no plan to fix it.

The reason is that the Tkinter is unstable on Mac OS. Looking at the python-tk provided by the Homebrew, applications implemented with Tkinter, like nvPY and IDLE, hang frequently. Honestly, it's not usable.

The above problem may be fixed/mitigated by tk/tcl debugging or GTK3 migration. But it requires a lot of work. Contributions are welcome.

**Comment by ernstki** [comment]
@m0rg5, for what it's worth, it seems to work fine (so far) with the appropriate libraries from MacPorts:

* python38
* py38-tkinter

I used `pip install --user pipx` followed by `pipx install nvpy` to get nvpy installed, although that's definitely not a requirement. To be honest, packages you install with pipx fall apart as soon as you upgrade Python to the next minor release through MacPorts, so I'm not even sure if it's _advisable_ to use pipx.
